### ISSUE TITLE
TODO Lists

### ISSUE THREAD

**Issue by valen214** [valen214/mhr_armor_search_react#4]
- [ ] add custom parameters (80%)
- [ ] allow use of imported functions in "add column prompt" ( two approaches, use other column as input argument, add function to src)
- [ ] horizontal scroll on stat table
- [ ] implement export everything and import everything (half way, - params definitions - default columns)
- [ ] add multiple profile pages
- [ ] add charm
- [ ] add common favorite skills by weapon
- [ ] allow live edit profile skills
- [ ] add a panel for toggling conditionals
- [ ] force override conditionals / lock (?)

## Ultimate
- [ ] add sort by stat column
- [ ] SEARCH ARMOR BY STAT
- [ ] SEARCH AMONG MULTIPLE STATs

## QoL
- [ ] Import from Links
- [ ] implement skills profile import (from external website)
- [ ] add favorite skills row/category
- [ ] add search for armor set skills

## Internal
- [ ] integrate StatProfile, SkillsProfiles, Column Description (add) into single source
- [ ] implement a better way to deal with default columns

## UX
- [ ] add help pages

## UI
- [ ] add code hint to edit column function src
- [ ] import by code
- [ ] add parameter slider
- [ ] rearrange buttons location
- [ ] allow data to be composited
- [ ] AddColumnPrompt: add help
- [x] use CodeMirror (or Monaco or Ace) in AddColumnPrompt
- [x] Add profile delete
- [x] add delete column
- [x] think of a way to implement adding stat column
### subtle
- [ ] replace sharpness option with something else
- [ ] increase collapse speed for small element

## Performance
- [ ] use `useContextSelector` in params panel

## Mostly done could need follow up
- [x] open with paste bin link (relocate code logic)
